### PR TITLE
feat: added alert component

### PR DESCRIPTION
**Pull request by abhisekgupta001**
Please review my first component (Alert component). 
Thank You :)

### CODE REVIEW

**Review by samflab — COMMENTED** [review]
Beautiful colors for the alert components. Just one thing, the close button is missing in the danger component. Please fix that.

**Comment by samflab** [comment]
On the home page, the button hover color seems off, please fix that too
image

**Review by NtshVrm — APPROVED** [review]

**Comment by shraddha15-creator** [comment]
I will suggest same changes as Masudha suggested, also I'm not able to scroll the side nav bar

**Comment by abhisekgupta001** [comment]
> Beautiful colors for the alert components. Just one thing, the close button is missing in the danger component. Please fix that.

Fixed.

**Comment by abhisekgupta001** [comment]
> I will suggest same changes as Masudha suggested, also I'm not able to scroll the side nav bar

Fixed those changes. And side bar is set to overflow-y: auto, so scroll bar appears when needed, right now there are few items so it won't appear.

**Comment by abhisekgupta001** [comment]
> On the home page, the button hover color seems off, please fix that too image

Fixed.

**Review by rutvikpumak — APPROVED** [review]

**Review by shraddha15-creator — APPROVED** [review]

**Pull request merged**
